language: node_js
node_js:
- '4'
- '6'

branches:
  only:
  - master

before_script:
- npm install
- npm run lint

script:
- npm test

after_success:
- if ! [[ "$TRAVIS_NODE_VERSION" == 4 ]]; then
- bash <(curl -s https://codecov.io/bash)
- fi
