language: node_js
node_js:
- '4'
- '6'

branches:
  only:
  - master
before_script:
- npm install
- npm run lint
script:
- npm run cover
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash)
